### PR TITLE
Not rendering children if the tree node is collapsed

### PR DESCRIPTION
**Pull request by sunjay**
I noticed that when rendering larger trees with quite a few branches/nodes and quite a few dom elements in each of them, I would often run out of memory very quickly. Even if I started with `defaultCollapsed={true}`, all the children were still be rendered so it didn't matter. 

With this change, collapsed nodes don't render their children at all.

I noticed that in your CSS you simply set `height: 0` when the tree is collapsed. That's viable for smaller trees and it avoids an unnecessary rerender when the tree gets uncollapsed, but for very large trees it stops working very quickly. 

By very large tree I mean less than 300 nodes which when you think about it, isn't that big at all.

### CODE REVIEW

**Comment by chenglou** [comment]
Humm... This would kill the unmounting animation though (and I don't wanna bring in react-motion or TransitionGroup or anything). Maybe that's fine?

**Comment by sunjay** [comment]
This could also be done as an option. We could call it trim or something and people could use it on their large trees to make the tree view destroy the children on close.

**Comment by sunjay** [comment]
@chenglou can we merge this or should we close it and leave it out?

**Comment by chenglou** [comment]
This makes sense. Can you remove the swap file? Then I'll merge it.

**Comment by sunjay** [comment]
@chenglou Swap file is gone. Good to go. :+1:

**Comment by chenglou** [comment]
Great, thanks!

**Pull request merged**
